controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    gripper_controller:
      type: effort_controllers/GripperActionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

gripper_controller:
  ros__parameters:
    action_monitor_rate: 200.0
    joint: robotiq_85_left_knuckle_joint
    goal_tolerance: 0.01
    max_effort: 0.05
    allow_stalling: true
    stall_velocity_threshold: 0.001
    stall_timeout: 2.0
    gains:
      gripper_joint: {p: 200, d: 1, i: 5, i_clamp: 1}

#gripper_controller:
#  ros__parameters:
#    joints:
#      - robotiq_85_left_knuckle_joint
#    interface_name: position