#-------------------------------------------------------------------------------
# Description:
#   The purpose of this service definition, is to define a way to get a
#   (partial) description of an ABB robot controller system.
#
# Note:
#   The description will be returned in a Google Protocol Buffer text format.
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# Service request fields
#-------------------------------------------------------------------------------

