#-------------------------------------------------------------------------------
# Description:
#   The purpose of this service definition, is to allow triggering a service
#   where the response includes both a numerical result code and a human
#   readable message.
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# Service request fields (none)
#-------------------------------------------------------------------------------

