controller_manager:
  ros__parameters:
    update_rate: 50 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    #gripper_controller:
    #  type: joint_trajectory_controller/JointTrajectoryController
    gripper_controller:
      type: position_controllers/GripperActionController


joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6

    write_op_modes:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    
    interface_name: position

    command_interfaces:
      - position
    
    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

    allow_partial_joints_goal: false # Defaults to false
    hardware_state_has_offset: true
    deduce_states_from_derivatives: true
    
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)


#gripper_controller:
#  ros__parameters:
#    command_interfaces:
#     - position
#    state_interfaces:
#      - position
#      - velocity
#    joints:
#      - drive_joint
#    interface_name: position

gripper_controller:
  ros__parameters:
    action_monitor_rate: 200.0
    joint: robotiq_85_left_knuckle_joint
    goal_tolerance: 0.01
    max_effort: 0.05
    allow_stalling: true
    stall_velocity_threshold: 0.001
    stall_timeout: 2.0
    gains:
      gripper_joint: {p: 200, d: 1, i: 5, i_clamp: 1}


