# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    car_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    command_interfaces:
      []
    state_interfaces:
      []
gripper_controller:
  ros__parameters:
    joint: drive_joint
    command_interfaces:
      []
    state_interfaces:
      []
car_controller:
  ros__parameters:
    joints:
      - wheel1_joint
      - wheel2_joint
      - wheel3_joint
      - wheel4_joint
    command_interfaces:
      []
    state_interfaces:
      []