arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 6.0
  kinematics_solver_timeout: 6.0
#gripper:
 # kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
 # kinematics_solver_search_resolution: 0.0050000000000000001
 # kinematics_solver_timeout: 0.0050000000000000001