# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    First Wheel_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    Second Wheel_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    Third Wheel_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    Fourth Wheel_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

First Wheel_controller:
  ros__parameters:
    joint: wheel1_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
Second Wheel_controller:
  ros__parameters:
    joint: wheel2_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
Third Wheel_controller:
  ros__parameters:
    joint: wheel3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
Fourth Wheel_controller:
  ros__parameters:
    joint: wheel4_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity